[render]
font = "local:NotoSans-Regular"

[source]
path = "keymap.c"
hscale = 7
vscale = 2

[remap]
"C|Esc" = "Ctrl·Esc"
"S|Entr" = "S·Enter"
"Nav|;" = "Nav · ;"
"Reset" = "Rst"
"Debug" = "Dbg"
"Qwerty" = "Qwr"
"AudOn" = "Aud\nON"
"AudOff" = "Aud\nOFF"
"AGnorm" = "AG\nnorm"
"AGswap" = "AG\nswap"
"Voice-" = "VO\n-"
"Voice+" = "VO\n+"
"MusOn" = "Mus\nON"
"MusOff" = "Mus\nOFF"
"MidiOn" = "Midi\nON"
"MidOff" = "Midi\nOFF"

[[label]]
position = "center"
layer = "Prog"

[[label]]
position = "top"
scale = 0.8
layer = "Raise"

[[label]]
position = "bottom"
scale = 0.8
layer = "Lower"

#[[label]]
#position = "top-right"
#scale = 0.8
#layer = "Navigation"
#ignore = [ "Shift", "Ctrl" ]

[[label]]
position = "left"
scale = 0.8
layer = "Accent"
ignore = [ "Shift" ]

[[label]]
position = "bottom-right"
scale = 0.5
layer = "Adjust (Lower + Raise)"
ignore = [ "Del" ]
